"""Compute current RQ1 statistics from merged evaluation records."""

from __future__ import annotations

import csv

import numpy as np

from analyze_rq1_accepted_profiles import (ARTIFACTS, FORMAL, OUTCOMES, OUTPUT, PAPER_TAB, formal_state, io_score,
                                           read_csv)


STAGES = ("accepted", "proof_failed")
EXPECTED_GROUPS = None
REPLICATES = 2_000
SEED = 20_260_826
# Every metric is coded so that higher is better. Unresolved I/O cases count as not passed;
# other unresolved or unavailable results stay missing. Dimensions follow the order of Table 1.
METRICS = (
    ("Text similarity", "BLEU", "score", "text_bleu"),
    ("Text similarity", "ROUGE-L", "score", "text_rouge_l"),
    ("Text similarity", "KeySpecMatch", "score", "text_key_spec_match"),
    ("Intent judgement", "Spec-code judgement", "score", "llm_spec_code_score"),
    ("Intent judgement", "Spec-spec judgement", "score", "llm_intent_score"),
    ("Semantic triviality", "No false precondition", "triviality", "triviality_pre_false_state"),
    ("Semantic triviality", "No true postcondition", "triviality", "triviality_post_true_state"),
    ("Specification correctness", "Soundness", "formal", "soundness"),
    ("Specification correctness", "Completeness", "formal", "completeness"),
    ("Specification correctness", "Equivalence", "formal", "equivalence"),
    ("Behavior correctness", "Correct-I/O acceptance", "io", "io_correct"),
    ("Behavior correctness", "Wrong-output rejection", "io", "io_wrong"),
    ("Behavior correctness", "Invalid-input rejection", "io", "io_invalid"),
)


def metric_values(rows: list[dict[str, str]], outcomes: dict[str, dict[str, str]]) -> dict[str, np.ndarray]:
    values = {}
    for _, name, kind, key in METRICS:
        if kind == "formal":
            codes = [{"pass": 1.0, "fail": 0.0}.get(formal_state(outcomes[row["sample_id"]], FORMAL[key]), np.nan)
                     for row in rows]
        elif kind == "io":
            codes = [io_score(outcomes[row["sample_id"]], key) for row in rows]
            codes = [np.nan if code is None else code for code in codes]
        elif kind == "triviality":
            codes = [{"favorable": 1.0, "unfavorable": 0.0}.get(row[key], np.nan) for row in rows]
        else:
            codes = [float(row[key]) if row[key] else np.nan for row in rows]
        values[name] = np.array(codes)
    return values


def tied_within(values: np.ndarray) -> int:
    """Pairs inside one acceptance group whose metric values differ."""
    counts = np.unique(values, return_counts=True)[1]
    return len(values) * (len(values) - 1) // 2 - int((counts * (counts - 1) // 2).sum())


def pair_counts(accepted: np.ndarray, values: np.ndarray) -> np.ndarray:
    """Concordant, discordant, acceptance-only tied, and metric-only tied pairs."""
    high, low = np.sort(values[accepted]), np.sort(values[~accepted])
    below, upto = np.searchsorted(low, high, "left"), np.searchsorted(low, high, "right")
    return np.array([below.sum(), (len(low) - upto).sum(), tied_within(high) + tied_within(low),
                     (upto - below).sum()], dtype=float)


def tau_b(counts: np.ndarray) -> float:
    concordant, discordant, left, right = counts[..., 0], counts[..., 1], counts[..., 2], counts[..., 3]
    denominator = np.sqrt((concordant + discordant + left) * (concordant + discordant + right))
    with np.errstate(invalid="ignore", divide="ignore"):
        return np.where(denominator > 0, (concordant - discordant) / denominator, np.nan)


def max_tau_b(accepted: np.ndarray, values: np.ndarray) -> float:
    """Largest tau-b reachable with the same group sizes and metric values."""
    best = np.zeros(len(values), dtype=bool)
    best[len(values) - accepted.sum():] = True
    return float(tau_b(pair_counts(best, np.sort(values))))


def interval(estimates: np.ndarray) -> tuple[float, float]:
    """Percentile interval; left empty when fewer than 95% of replicates are defined."""
    valid = estimates[np.isfinite(estimates)]
    if valid.size < np.ceil(0.95 * estimates.size):
        return np.nan, np.nan
    low, high = np.quantile(valid, (0.025, 0.975))
    return float(low), float(high)


def signed(value: float) -> str:
    return f"{value:.3f}".replace("-", "$-$")


def write_table(rows: list[dict[str, object]]) -> None:
    lines = ["% Generated by RQs/RQ1/scripts/analyze_rq1_acceptance_association.py.",
             r"\begin{table}[t]", r"\caption{Quality metrics of accepted and proof-failed artifacts.}",
             r"\label{tab:acceptance-association}", r"\centering\footnotesize", r"\setlength{\tabcolsep}{4pt}",
             r"\begin{tabular}{@{}llrrrc@{}}", r"\toprule",
             r" & & \multicolumn{2}{c}{Mean} & \multicolumn{2}{c}{$\tau_b$ with acceptance} \\",
             r"\cmidrule(lr){3-4}\cmidrule(lr){5-6}",
             r"Dimension & Metric & Accepted & Proof-failed & Value & 95\% CI \\",
             r"\midrule"]
    previous = None
    for row in rows:
        if previous is not None and row["dimension"] != previous:
            lines.append(r"\addlinespace")
        dimension = row["dimension"] if row["dimension"] != previous else ""
        previous = row["dimension"]
        metric = str(row["metric"]).replace("Spec-", "Spec--")
        ci = f"[{signed(row['ci_low'])}, {signed(row['ci_high'])}]" if np.isfinite(row["ci_low"]) else "--"
        lines.append(f"{dimension} & {metric} & {row['accepted_mean']:.3f} & {row['proof_failed_mean']:.3f} & "
                     f"{signed(row['tau_b'])} & {ci} \\\\")
    lines.extend([r"\bottomrule", r"\end{tabular}", r"\end{table}", ""])
    (PAPER_TAB / "rq1_acceptance_association.tex").write_text("\n".join(lines), encoding="utf-8")


def write_csv(name: str, rows: list[dict[str, object]]) -> None:
    with (OUTPUT / name).open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=list(rows[0]))
        writer.writeheader()
        writer.writerows(rows)


def main() -> None:
    rows = [row for row in read_csv(ARTIFACTS) if row["verification_stage"] in STAGES]
    accepted = np.array([row["verification_stage"] == "accepted" for row in rows])
    if EXPECTED_GROUPS is not None:
        assert (accepted.sum(), (~accepted).sum()) == EXPECTED_GROUPS
    OUTPUT.mkdir(parents=True, exist_ok=True)
    PAPER_TAB.mkdir(parents=True, exist_ok=True)
    outcomes = {row["sample_id"]: row for row in read_csv(OUTCOMES)}
    values = metric_values(rows, outcomes)

    task_ids = sorted({row["task_id"] for row in rows})
    task_codes = np.searchsorted(task_ids, [row["task_id"] for row in rows])
    members = [np.flatnonzero(task_codes == task) for task in range(len(task_ids))]
    within = {name: np.array([pair_counts(accepted[m], y[m]) for m in (idx[~np.isnan(y[idx])] for idx in members)])
              for name, y in values.items()}

    rng = np.random.default_rng(SEED)
    weights = np.zeros((REPLICATES, len(task_ids)))
    pooled = {name: np.full(REPLICATES, np.nan) for name in values}
    for replicate in range(REPLICATES):
        pick = rng.integers(len(task_ids), size=len(task_ids))
        weights[replicate] = np.bincount(pick, minlength=len(task_ids))
        sample = np.concatenate([members[task] for task in pick])
        for name, y in values.items():
            keep = sample[~np.isnan(y[sample])]
            pooled[name][replicate] = tau_b(pair_counts(accepted[keep], y[keep]))

    summary = []
    for dimension, name, kind, _ in METRICS:
        y = values[name]
        ok = ~np.isnan(y)
        counts = pair_counts(accepted[ok], y[ok])
        summary.append({
            "dimension": dimension, "metric": name, "kind": "binary" if kind in ("formal", "triviality") else "score",
            "accepted_n": int((ok & accepted).sum()), "proof_failed_n": int((ok & ~accepted).sum()),
            "accepted_mean": float(y[ok & accepted].mean()), "proof_failed_mean": float(y[ok & ~accepted].mean()),
            "concordant": int(counts[0]), "discordant": int(counts[1]),
            "acceptance_only_ties": int(counts[2]), "metric_only_ties": int(counts[3]),
            "tau_b": float(tau_b(counts)), **dict(zip(("ci_low", "ci_high"), interval(pooled[name]))),
            "max_tau_b": max_tau_b(accepted[ok], y[ok]),
            "within_task_tau_b": float(tau_b(within[name].sum(axis=0))),
            **dict(zip(("within_ci_low", "within_ci_high"), interval(tau_b(weights @ within[name])))),
        })
    write_csv("rq1_acceptance_association.csv", summary)
    write_table(summary)

    write_csv("rq1_acceptance_artifacts.csv", [
        {"sample_id": row["sample_id"], "task_id": row["task_id"], "accepted": int(flag),
         **{name: ("" if np.isnan(values[name][index]) else values[name][index]) for name in values}}
        for index, (row, flag) in enumerate(zip(rows, accepted))])

    print(f"{accepted.sum():,} accepted and {(~accepted).sum():,} proof-failed artifacts from {len(task_ids)} tasks")
    for row in summary:
        print(f"{row['metric']:<24} n={row['accepted_n']:>5}/{row['proof_failed_n']:<5} "
              f"mean={row['accepted_mean']:.3f}/{row['proof_failed_mean']:.3f} "
              f"tau_b={row['tau_b']:+.3f} [{row['ci_low']:+.3f}, {row['ci_high']:+.3f}] max={row['max_tau_b']:+.3f} "
              f"within={row['within_task_tau_b']:+.3f} [{row['within_ci_low']:+.3f}, {row['within_ci_high']:+.3f}]")


if __name__ == "__main__":
    main()
