"""Build RQ1 tables from the final merged evaluation records."""
from __future__ import annotations

import argparse
import csv
import hashlib
import json
import math
import os
import shutil
from collections import Counter
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
from matplotlib.patches import Circle, Rectangle

import analyze_rq1_accepted_profiles as profiles
import analyze_rq1_acceptance_association as association
import rq1_paths
from analyze_rq1_accepted_profiles import FORMAL, IO, formal_state, io_state, read_csv, triviality_state
from analyze_rq1_acceptance_association import pair_counts, tau_b

ROOT = Path(__file__).resolve().parents[3]
PAPER = ROOT / "RQs/RQ1"
CHECKS = ("equivalence", "io", "triviality")
ORDER = ("100", "010", "001", "110", "101", "011", "111", "000")
DIRECTIONS = ("pre_ref_to_gen", "post_gen_to_ref", "pre_gen_to_ref", "post_ref_to_gen")
PER_FILE_METRICS = {"io_correct": "correct_io_pass_rate", "io_invalid": "invalid_test_filtering_rate"}
# Case checks that ran without reaching a decision; every other undetermined reason means the check could not run.
UNDECIDED = {"verification_unresolved", "timeout", "runtime_timeout", "runtime_or_requires_unknown", "input_admission_unresolved", "output_rejection_unresolved"}


def verify_association(rows: list[dict], encoded: list[dict]) -> None:
    """Recalculate sample counts, means and tau from the saved artifact scores."""
    assert len({r["sample_id"] for r in encoded}) == len(encoded)
    for row in rows:
        metric = row["metric"]
        usable = [r for r in encoded if r[metric] != ""]
        accepted = np.array([r["accepted"] == "1" for r in usable])
        values = np.array([float(r[metric]) for r in usable])
        assert np.isfinite(values).all(), metric
        assert int(accepted.sum()) == int(row["accepted_n"]), metric
        assert int((~accepted).sum()) == int(row["proof_failed_n"]), metric
        assert math.isclose(float(values[accepted].mean()), float(row["accepted_mean"]), abs_tol=1e-12), metric
        assert math.isclose(float(values[~accepted].mean()), float(row["proof_failed_mean"]), abs_tol=1e-12), metric
        assert math.isclose(float(tau_b(pair_counts(accepted, values))), float(row["tau_b"]), abs_tol=1e-12), metric

def write_table(rows: list[dict], source_note: str | None = None) -> None:
    lines = [
        "% Generated by RQs/RQ1/scripts/refresh_rq1_paper.py.",
        r"\begin{table}[t]",
        r"\caption{Quality metrics of accepted and proof-failed artifacts. A dash marks an undefined interval.}",
        r"\label{tab:acceptance-association}", r"\centering\footnotesize",
        r"\setlength{\tabcolsep}{3pt}", r"\begin{tabular}{@{}llrrrrrc@{}}", r"\toprule",
        r" & & \multicolumn{2}{c}{Accepted} & \multicolumn{2}{c}{Proof-failed} & \multicolumn{2}{c}{$\tau_b$ with acceptance} \\",
        r"\cmidrule(lr){3-4}\cmidrule(lr){5-6}\cmidrule(lr){7-8}",
        r"Dimension & Metric & $n$ & Mean & $n$ & Mean & Value & 95\% CI \\", r"\midrule",
    ]
    labels = {"No false precondition": "False precondition not proved", "No true postcondition": "True postcondition not proved"}
    # The dimension spans its metric rows in two short lines, as in the metric catalog table.
    groups: dict[str, list[dict]] = {}
    for row in rows:
        groups.setdefault(row["dimension"], []).append(row)
    for i, (dimension, members) in enumerate(groups.items()):
        if i:
            lines.append(r"\addlinespace[2pt]")
        first, _, rest = dimension.partition(" ")
        label = r"\multirow{" + str(len(members)) + r"}{*}{\shortstack[l]{" + first + r"\\" + rest + "}}"
        for j, row in enumerate(members):
            metric = labels.get(row["metric"], row["metric"].replace("Spec-", "Spec--"))
            low, high = float(row["ci_low"]), float(row["ci_high"])
            ci = f"[{low:.3f}, {high:.3f}]" if math.isfinite(low) and math.isfinite(high) else "--"
            tau = f"{float(row['tau_b']):.3f}".replace("-", "$-$")
            lines.append(
                f"{label if j == 0 else ''} & {metric} & {int(row['accepted_n']):,} & {float(row['accepted_mean']):.3f} & "
                f"{int(row['proof_failed_n']):,} & {float(row['proof_failed_mean']):.3f} & {tau} & {ci} " + r"\\"
            )
    lines.extend([r"\bottomrule", r"\end{tabular}", r"\end{table}", ""])
    if source_note:
        lines.insert(1, "% " + source_note)
    (PAPER / "tables/rq1_acceptance_association.tex").write_text("\n".join(lines), encoding="utf-8")

def refresh_table4(source_root: Path) -> None:
    """Update only Table 4 from materialized records, without replaying overlays."""
    source_root = source_root.absolute()
    paths = {"labels": source_root / "rq1_artifact_labels.csv",
             "outcomes": source_root / "rq1_artifact_outcomes.csv",
             "validation": source_root / "provenance/validation.json"}
    input_hashes = {str(p.relative_to(ROOT)): hashlib.sha256(p.read_bytes()).hexdigest()
                    for p in paths.values()}
    validation = json.loads(paths["validation"].read_text(encoding="utf-8"))
    assert validation["status"] == "complete", "The source migration must be complete"
    labels, outcomes = read_csv(paths["labels"]), read_csv(paths["outcomes"])
    labels_by_id = {r["sample_id"]: r for r in labels}
    outcomes_by_id = {r["sample_id"]: r for r in outcomes}
    assert len(labels_by_id) == len(labels) and len(outcomes_by_id) == len(outcomes)
    assert labels_by_id.keys() == outcomes_by_id.keys()
    assert all(r["verification_stage"] == outcomes_by_id[s]["verification_stage"]
               and r["task_id"] == outcomes_by_id[s]["task_id"]
               and r["analysis_eligible"] == "True" for s, r in labels_by_id.items())
    selected = [r for r in labels if r["verification_stage"] in association.STAGES]
    groups = Counter(r["verification_stage"] for r in selected)
    assert all(groups[stage] > 0 for stage in association.STAGES)
    output = rq1_paths.RESULTS
    output.mkdir(parents=True, exist_ok=True)
    summary_path = output / "summary.json"
    summary = {"status": "in_progress", "source_sha256": input_hashes,
               "groups": dict(groups), "tasks": len({r["task_id"] for r in selected}),
               "bootstrap_unit": "task", "bootstrap_replicates": association.REPLICATES,
               "bootstrap_seed": association.SEED,
               "verus_evidence_release": validation["verus_evidence_release"]}
    summary_path.write_text(json.dumps(summary, indent=2) + "\n", encoding="utf-8")
    association.ARTIFACTS, association.OUTCOMES = paths["labels"], paths["outcomes"]
    association.OUTPUT, association.PAPER_TAB = output, output
    association.EXPECTED_GROUPS = tuple(groups[stage] for stage in association.STAGES)
    association.main()
    rows = read_csv(output / "rq1_acceptance_association.csv")
    encoded = read_csv(output / "rq1_acceptance_artifacts.csv")
    assert len(rows) == len(association.METRICS)
    assert {r["sample_id"] for r in encoded} == {r["sample_id"] for r in selected}
    verify_association(rows, encoded)
    for path, digest in input_hashes.items():
        assert hashlib.sha256((ROOT / path).read_bytes()).hexdigest() == digest
    write_table(rows, source_note=(
        f"Analysis: {(output / 'rq1_acceptance_association.csv').relative_to(ROOT)}; "
        f"sources: {paths['labels'].relative_to(ROOT)}, {paths['outcomes'].relative_to(ROOT)}; "
        f"{association.REPLICATES} task bootstrap replicates; seed {association.SEED}."))
    table_path = PAPER / "tables/rq1_acceptance_association.tex"
    (output / "rq1_acceptance_association.tex").write_bytes(table_path.read_bytes())
    summary.update(status="complete", metrics=len(rows),
                   table=str(table_path.relative_to(ROOT)),
                   table_sha256=hashlib.sha256(table_path.read_bytes()).hexdigest(),
                   code_sha256={str(p.relative_to(ROOT)): hashlib.sha256(p.read_bytes()).hexdigest()
                                for p in (Path(__file__), Path(association.__file__), Path(profiles.__file__), Path(rq1_paths.__file__))},
                   result_sha256={str(p.relative_to(ROOT)): hashlib.sha256(p.read_bytes()).hexdigest()
                                  for p in (output / 'rq1_acceptance_association.csv', output / 'rq1_acceptance_artifacts.csv',
                                            output / 'rq1_acceptance_association.tex')},
                   checks="Unique sample keys, matching stages and tasks; all counts, means and tau verified against encoded scores.")
    summary_path.write_text(json.dumps(summary, indent=2) + "\n", encoding="utf-8")
    print(f"Updated Table 4 from {source_root.relative_to(ROOT)}; evidence: {output.relative_to(ROOT)}")

def draw_venn(summary: dict) -> None:
    """Equal circles keep all seven regions readable; counts, not areas, encode frequency.

    The landscape layout is drawn at its printed size, so the paper includes it without scaling.
    """
    from matplotlib import font_manager
    from matplotlib.patches import FancyBboxPatch

    base = Path.home() / ".TinyTeX/texmf-dist/fonts/opentype/public/libertine"
    family = "serif"
    if (base / "LinLibertine_R.otf").exists():
        # Linux Libertine matches the acmart body font.
        for name in ("LinLibertine_R.otf", "LinLibertine_RB.otf", "LinLibertine_RI.otf"):
            font_manager.fontManager.addfont(str(base / name))
        family = "Linux Libertine O"
    # The PDF goes through LaTeX (pgf) so the figure uses the paper's Type 1 Libertine fonts.
    if shutil.which("pdflatex") is None and (Path.home() / ".TinyTeX/bin/x86_64-linux").exists():
        os.environ["PATH"] = f"{Path.home() / '.TinyTeX/bin/x86_64-linux'}{os.pathsep}{os.environ['PATH']}"
    plt.rcParams.update({
        "font.family": family, "font.size": 8, "pgf.texsystem": "pdflatex", "pgf.rcfonts": False,
        "pgf.preamble": r"\usepackage[T1]{fontenc}\usepackage{libertine}",
    })
    regions = summary["venn_regions"]
    incomplete = summary["venn_regions_with_indeterminate_check"]
    marginals = summary["venn_marginals"]
    ink, muted = "#222222", "#6B6B6B"
    sets = [  # key, centre, colour, label anchor, alignment
        ("equivalence", (-0.58, 0.36), "#0072B2", (-1.6, 1.16), "right"),
        ("io", (0.58, 0.36), "#D55E00", (1.6, 1.16), "left"),
        ("triviality", (0.0, -0.64), "#009E73", (0.96, -1.2), "left"),
    ]
    names = {"equivalence": ("Contract", "comparison"), "io": ("I/O suite",), "triviality": ("Triviality",)}
    inches_per_unit = 0.6  # one unit is the circle radius
    x0, x1, y0, y1 = -2.95, 2.95, -1.84, 1.5
    fig, ax = plt.subplots(figsize=((x1 - x0) * inches_per_unit, (y1 - y0) * inches_per_unit))
    ax.set_aspect("equal")
    ax.add_patch(FancyBboxPatch((x0 + 0.04, y0 + 0.04), x1 - x0 - 0.08, y1 - y0 - 0.08,
                                boxstyle="round,pad=0,rounding_size=0.12",
                                facecolor="#F6F6F4", edgecolor="#C8C8C8", linewidth=0.6, zorder=0))
    for key, centre, colour, (x, y), align in sets:
        ax.add_patch(Circle(centre, 1.0, facecolor=colour, alpha=0.13, edgecolor="none", zorder=1))
        ax.add_patch(Circle(centre, 1.0, facecolor="none", edgecolor=colour, linewidth=1.1, zorder=3))
        for i, line in enumerate(names[key]):
            ax.text(x, y - 0.23 * i, line, ha=align, va="baseline", color=colour, fontweight="bold", fontsize=8)
        ax.text(x, y - 0.23 * len(names[key]) - 0.02, f"{marginals[key]:,} flagged",
                ha=align, va="baseline", color=colour, fontsize=7.5)
    positions = {
        "100": (-1.0, 0.56), "010": (1.0, 0.56), "001": (0.0, -1.14),
        "110": (0.0, 0.86), "101": (-0.64, -0.2), "011": (0.64, -0.2), "111": (0.0, -0.03),
    }
    for key, (x, y) in positions.items():
        ax.text(x, y, f"{regions[key]:,}", ha="center", va="center", fontsize=8.5, fontweight="bold", color=ink, zorder=4)
        if incomplete[key]:
            ax.text(x, y - 0.24, f"({incomplete[key]:,})", ha="center", va="center", fontsize=7, color=muted, zorder=4)
    joint = summary["joint_pass_available_cases"]
    ax.text(-0.96, -1.2, f"No flag: {regions['000']:,}", ha="right", va="baseline", fontsize=8, fontweight="bold", color=ink)
    ax.text(-0.96, -1.45, f"{joint:,} pass all checks", ha="right", va="baseline", fontsize=7.5, color=muted)
    ax.text(-0.96, -1.66, f"({incomplete['000']:,}) incomplete", ha="right", va="baseline", fontsize=7.5, color=muted)
    ax.set_xlim(x0, x1)
    ax.set_ylim(y0, y1)
    ax.axis("off")
    fig.subplots_adjust(0, 0, 1, 1)
    fig.savefig(PAPER / "figures/rq1_check_overlap.pdf", backend="pgf", pad_inches=0)
    fig.savefig(OUTPUT / "rq1_check_overlap.png", dpi=300, pad_inches=0)
    plt.close(fig)

def write_figure(summary: dict) -> None:
    regions = summary["venn_regions"]
    lines = [r"\begin{figure}[t]", r"\centering", r"\includegraphics{fig/rq1_check_overlap.pdf}"]
    lines.append(
        r"\caption{Screening flags of the " + f"{summary['venn_population']:,}"
        + r" accepted artifacts, with counts of incomplete checks in parentheses.}"
    )
    lines.append(
        r"\Description{The contract-comparison-only, I/O-only, triviality-only, contract-comparison-and-I/O-only, contract-comparison-and-triviality-only, I/O-and-triviality-only, and all-three regions contain "
        + ", ".join(str(regions[k]) for k in ORDER[:-1])
        + f" artifacts. Outside all three circles are {regions['000']} artifacts." + "}"
    )
    lines.extend([r"\label{fig:rq1-check-overlap}", r"\end{figure}", ""])
    (PAPER / "figure_captions/rq1_check_overlap.tex").write_text("\n".join(lines), encoding="utf-8")
if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source-root", type=Path, default=ROOT / "data/evaluation")
    args = parser.parse_args()
    for name in ("tables", "figures", "figure_captions"):
        (PAPER / name).mkdir(parents=True, exist_ok=True)
    refresh_table4(args.source_root)
