from __future__ import annotations

from .catalog import AVAILABLE_METRIC_IDS, DEFAULT_ENABLED_METRIC_IDS, EXTENSION_METRIC_IDS, METRIC_CATALOG
from .share.config import set_verus_binary
from .share.text import (
    TEXT_METRIC_FULL,
    TEXT_METRIC_SPEC_ONLY,
    TEXT_METRIC_SCOPES,
    get_text_metric_inputs,
    get_text_metric_scope,
    normalize_text_metric_scope,
    text_metric_scope,
)
from .registry import (
    METRIC_FUNCTIONS,
    compute_all_metrics,
    metric_correct_io_pass_rate,
    metric_invalid_test_filtering_rate,
    metric_llm_as_judge,
    metric_llm_as_judge_intent_consistency,
    metric_llm_as_judge_spec_code_intent_consistency,
    metric_mutation_kill_rate,
    metric_pass,
    metric_parse_rate,
    metric_postcondition_clause_completeness_rate,
    metric_postcondition_clause_reliability_rate,
    metric_precondition_clause_completeness_rate,
    metric_precondition_clause_reliability_rate,
    metric_proportion_at_least_gt,
    metric_proportion_at_most_gt,
    metric_proportion_ge_gt,
    metric_proportion_le_gt,
    metric_redundancy_rate,
    metric_spec_redundancy_rate,
    metric_spec_size_complexity,
    metric_spec_size_complexity_proof,
    metric_spec_size_complexity_spec_only,
    metric_trivial_spec_ratio,
    metric_type_check_rate,
    metric_verification_pass_rate,
    metric_verification_time,
    metric_verus_spec_score,
    metric_verus_textual_similarity,
    metric_verus_textual_similarity_spec_only,
    metric_verus_textual_similarity_proof,
    metric_wrong_io_reject_rate,
)

# Compatibility aliases for callers previously relying on the legacy ``metrics``
# package's top-level namespace (e.g. web_app.py). The new package registers the
# 24 base metrics listed in catalog.py and has no "table-disabled" concept, so
# the disabled tuple is empty; ALL_METRIC_FUNCTIONS mirrors METRIC_FUNCTIONS.
DISABLED_BY_TABLE_METRIC_IDS: tuple[str, ...] = ()
ALL_METRIC_FUNCTIONS = METRIC_FUNCTIONS

__all__ = [
    "ALL_METRIC_FUNCTIONS",
    "AVAILABLE_METRIC_IDS",
    "DEFAULT_ENABLED_METRIC_IDS",
    "DISABLED_BY_TABLE_METRIC_IDS",
    "EXTENSION_METRIC_IDS",
    "METRIC_CATALOG",
    "METRIC_FUNCTIONS",
    "TEXT_METRIC_FULL",
    "TEXT_METRIC_SCOPES",
    "TEXT_METRIC_SPEC_ONLY",
    "compute_all_metrics",
    "get_text_metric_inputs",
    "get_text_metric_scope",
    "normalize_text_metric_scope",
    "set_verus_binary",
    "text_metric_scope",
    "metric_correct_io_pass_rate",
    "metric_invalid_test_filtering_rate",
    "metric_llm_as_judge",
    "metric_llm_as_judge_intent_consistency",
    "metric_llm_as_judge_spec_code_intent_consistency",
    "metric_mutation_kill_rate",
    "metric_pass",
    "metric_parse_rate",
    "metric_postcondition_clause_completeness_rate",
    "metric_postcondition_clause_reliability_rate",
    "metric_precondition_clause_completeness_rate",
    "metric_precondition_clause_reliability_rate",
    "metric_proportion_at_least_gt",
    "metric_proportion_at_most_gt",
    "metric_proportion_ge_gt",
    "metric_proportion_le_gt",
    "metric_redundancy_rate",
    "metric_spec_redundancy_rate",
    "metric_spec_size_complexity",
    "metric_spec_size_complexity_spec_only",
    "metric_spec_size_complexity_proof",
    "metric_trivial_spec_ratio",
    "metric_type_check_rate",
    "metric_verification_pass_rate",
    "metric_verification_time",
    "metric_verus_spec_score",
    "metric_verus_textual_similarity",
    "metric_verus_textual_similarity_spec_only",
    "metric_verus_textual_similarity_proof",
    "metric_wrong_io_reject_rate",
]
