"""Generate the RQ3 paper tables from the validated analyses."""
from pathlib import Path

from rq3_io_common import ROOT, RESULTS, file_hash, read_csv, read_json, write_json


def refresh():
    summary_path = RESULTS / "variants/summary.json"
    validation = read_json(RESULTS / "validation.json")
    assert validation["status"] == "complete"
    assert validation["summary_sha256"] == file_hash(summary_path)
    for record in (read_json(summary_path), read_json(RESULTS / "natural/summary.json")):
        for name, expected in record["source_sha256"].items():
            assert file_hash(ROOT / name) == expected, name
    paper = ROOT / "RQs/RQ3/tables"
    conditional = RESULTS / "natural/conditional_rates.csv"
    selection_path = RESULTS / "variants/operator_selection.csv"
    matrix_path = RESULTS / "variants/detection_matrix.csv"
    models = {"llama": "Llama", "gpt-4o": "GPT-4o", "deepseek-chat": "DeepSeek-Chat",
              "deepseek-reasoner": "DeepSeek-Reasoner", "qwen-coder": "Qwen-Coder"}
    rows = [r for r in read_csv(conditional) if r["scope"] == "available_cases_rq1" and r["workflow"] != "ALL"]
    by_config = {(r["workflow"], r["model"], r["shot"]): r for r in rows}
    pairs = sorted({(w, m) for w, m, _ in by_config})
    workflows = {"VerusAge": "VeruSAGE"}
    shots = ("zero-shot", "few-shot")

    def cells(accepted, passed, proved):
        return [f"{accepted:,}", f"{100 * passed / accepted:.1f}", f"{100 * proved / passed:.1f}"]

    lines = [
        "% Generated by RQs/RQ3/scripts/refresh_rq3_paper.py from results/natural/conditional_rates.csv.",
        r"\begin{table}[t]",
        r"\caption{Accepted artifacts (Acc.), \% passing I/O, and \% of those proved equivalent (Equiv.) by configuration.}",
        r"\label{tab:rq3-conditional}", r"\centering\footnotesize",
        r"\begin{tabular}{@{}llrrrrrr@{}}", r"\toprule",
        r" & & \multicolumn{3}{c}{Zero-shot} & \multicolumn{3}{c}{Few-shot} \\",
        r"\cmidrule(lr){3-5}\cmidrule(lr){6-8}",
        r"Workflow & Model & Acc. & I/O & Equiv. & Acc. & I/O & Equiv. \\",
        r"\midrule",
    ]
    for i, (workflow, model) in enumerate(pairs):
        members = sum(w == workflow for w, _ in pairs)
        first = i == 0 or pairs[i - 1][0] != workflow
        if first and i:
            lines.append(r"\addlinespace[2pt]")
        label = (r"\multirow{" + str(members) + "}{*}{" + workflows.get(workflow, workflow) + "}") if first else ""
        values = []
        for shot in shots:
            r = by_config[workflow, model, shot]
            values += cells(int(r["accepted"]), int(r["io_passed"]), int(r["equivalence_proved_given_io_pass"]))
        lines.append(" & ".join([label, models[model], *values]) + r" \\")
    total = []
    for shot in shots:
        members = [r for r in rows if r["shot"] == shot]
        total += cells(*(sum(int(r[k]) for r in members) for k in ("accepted", "io_passed", "equivalence_proved_given_io_pass")))
    lines += [r"\midrule", " & ".join(["All", "", *total]) + r" \\"]
    lines += [r"\bottomrule", r"\end{tabular}", r"\end{table}"]
    natural_table = paper / "rq3_conditional_quality.tex"
    natural_table.write_text("\n".join(lines) + "\n")

    selections = {r["operator"]: r for r in read_csv(selection_path)}
    cells = {(r["operator"], r["category"]): r for r in read_csv(matrix_path)}
    # Directions follow the obligations in Table 2: each change violates exactly one of L1--L4.
    directions = [
        ("pre_strengthening", ("Stronger", "precondition"), "$L_1$", ("PRE_ADD", "PRE_REFINE")),
        ("pre_weakening", ("Weaker", "precondition"), "$L_3$", ("PRE_REMOVE", "PRE_RELAX")),
        ("post_strengthening", ("Stronger", "postcondition"), "$L_4$", ("POST_ADD", "POST_REFINE")),
        ("post_weakening", ("Weaker", "postcondition"), "$L_2$", ("POST_REMOVE", "POST_RELAX")),
    ]
    kinds = ("positive", "negative", "invalid", "union")
    body, totals, diagnostic = [], [0] * 6, []
    for i, (direction, (first, second), obligation, operators) in enumerate(directions):
        if i:
            body.append(r"\addlinespace[2pt]")
        for j, op in enumerate(operators):
            assert selections[op]["direction"] == direction
            union = cells[op, "union"]
            assert int(union["unresolved"]) == 0, "Add an unresolved column if this changes"
            counts = [int(selections[op]["retained"])] + [int(cells[op, k]["behavior_detected"]) for k in kinds] + [int(union["missed"])]
            totals = [a + b for a, b in zip(totals, counts)]
            if int(union["diagnostic_only"]):
                diagnostic.append((op, int(union["diagnostic_only"])))
            label = (r"\multirow{2}{*}{\shortstack[l]{" + first + r"\\" + second + "}}") if j == 0 else ""
            violated = (r"\multirow{2}{*}{" + obligation + "}") if j == 0 else ""
            body.append(" & ".join([label, violated, op.split("_")[1].title(), *(f"{c:,}" for c in counts)]) + r" \\")
    assert {op for op, _ in diagnostic} <= {"POST_REMOVE", "POST_RELAX"}, "Update the caption note"
    words = {1: "one", 2: "two", 3: "three", 4: "four", 5: "five", 6: "six", 7: "seven", 8: "eight", 9: "nine"}
    count = sum(n for _, n in diagnostic)
    note = f"{words.get(count, count)} weaker postcondition" + ("s" if count != 1 else "")
    lines = [
        "% Generated by RQs/RQ3/scripts/refresh_rq3_paper.py from results/variants/.",
        r"\begin{table}[t]",
        r"\caption{Detection of controlled contract variants by kind of case. Missed variants pass every case, and " + note + (r" yields" if count == 1 else r" yield") + r" only expression diagnostics.}",
        r"\label{tab:io-detection}", r"\centering\footnotesize",
        r"\setlength{\tabcolsep}{4pt}", r"\begin{tabular}{@{}lllrrrrrr@{}}", r"\toprule",
        r"Change & Violates & Operation & $n$ & Correct & Wrong & Invalid & Detected & Missed \\",
        r"\midrule",
        *body,
        r"\midrule",
        " & ".join(["Total", "", "", *(f"{c:,}" for c in totals)]) + r" \\",
        r"\bottomrule", r"\end{tabular}", r"\end{table}",
    ]
    detection_table = paper / "rq3_io_detection.tex"
    detection_table.write_text("\n".join(lines) + "\n")
    write_json(RESULTS / "paper_tables_manifest.json", {
        "status": "complete",
        "source_sha256": {str(p.relative_to(ROOT)): file_hash(p) for p in
                          (conditional, selection_path, matrix_path, summary_path, RESULTS / "validation.json", Path(__file__))},
        "output_sha256": {str(p.relative_to(ROOT)): file_hash(p) for p in (natural_table, detection_table)},
    })
    print("Generated RQ3 conditional-quality and eight-operator detection tables.")


if __name__ == "__main__":
    refresh()
